[project]
name = 'Identity-for-Financial-Services'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.consent-tracking]
path = 'contracts/consent-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.credential-management]
path = 'contracts/credential-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
